//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindYourJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int EducationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string InstituteName { get; set; }
        public string TitleOfEducation { get; set; }
        public string Degree { get; set; }
        public Nullable<System.DateTime> FromYear { get; set; }
        public Nullable<System.DateTime> ToYear { get; set; }
        public string City { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
