//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindYourJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobPost()
        {
            this.JobApplies = new HashSet<JobApply>();
        }
    
        public int JobPostsID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> JobCategoryID { get; set; }
        public Nullable<int> RequiredPerson { get; set; }
        public string Qualification { get; set; }
        public string MinimumExperience { get; set; }
        public Nullable<int> AgeLimit { get; set; }
        public string MarritalStatus { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> ShortlistDate { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public Nullable<int> JobStatusID { get; set; }
        public string Description { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobApply> JobApplies { get; set; }
        public virtual JobCategory JobCategory { get; set; }
        public virtual Job Job { get; set; }
        public virtual JobStatu JobStatu { get; set; }
        public virtual User User { get; set; }
    }
}
